### PR TITLE
Mark python-language-server broken packages

### PR DESCRIPTION
**Pull request by ccordoba12**
All these packages are broken because they don't declare a top constraint on ujson, which is part of the package itself:

https://github.com/palantir/python-language-server/blob/143d9931cd0cabe92e1370b344cb02c406e0b0f1/setup.py#L41

See https://github.com/conda-forge/python-language-server-feedstock/pull/48 for more context.

This was really my fault. The ujson project had its `1.35.0` release more than three years ago so I didn't consider necessary to add that constraint. However, it was revived a month ago by the community with a new `2.0.0` release.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge/core, a little help here. Thanks!

**Comment by ccordoba12** [comment]
Also pinging @jjhelmus about this problem. These versions require a hotfix in the Anaconda side.

**Comment by jakirkham** [comment]
Thanks Carlos! 😄

**Comment by ccordoba12** [comment]
No problem :+1:

**Comment by jjhelmus** [comment]
The existing `python-language-server` packages in Anaconda's `main` repository have been hotfixed to require `ujson <=1.35`.  

For reference this was done in AnacondaRecipes/repodata-hotfixes#77

**Comment by ccordoba12** [comment]
Great! Thanks for the quick response!

**Pull request merged**
