### PR TITLE
Mark cachetools as broken

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist:

* [ ] Added a link to the relevant issue in the PR description.
* [ ] Pinged the team for the package.
<!
  For example if you are trying to mark a python package as broken.

      ping @conda-forge/python
!>

### CODE REVIEW

**Comment by isuruf** [comment]
Please see the checklist above.

**Comment by marcelotrevisani** [comment]
well, just by mistake I added a wrong python constrain for ``cachetools``
it is ``python >=3.5,<3.6`` and it should be just ``python >=3.5``

**Comment by beckermr** [comment]
This might be better as a repodata patch?

**Comment by isuruf** [comment]
No, neither is needed. build 0 has a requirement that is too strict. If there is a new build with a looser pin, no need to change anything.

**Pull request closed without merging**
