### PR TITLE
Remove broken Sphinxdft version

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist:

* [x] Added a link to the relevant issue in the PR description.
* [x] Pinged the team for the package.
<!
  For example if you are trying to mark a python package as broken.

      ping @conda-forge/python
!>

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge/sphinxdft - remove broken package

**Comment by jakirkham** [comment]
What was the issue with this package?

**Comment by jan-janssen** [comment]
The calculation fail when trying to access the `prce` library - this seems to be related to https://github.com/conda-forge/sphinxdft-feedstock/pull/8

**Comment by jan-janssen** [comment]
You can test it with https://github.com/jan-janssen/sphinx-example in the example we enforce the previous version, but if you update the example no longer works https://github.com/jan-janssen/sphinx-example

**Comment by jan-janssen** [comment]
@jakirkham Can you please merge this pull request, as we have more and more users upgrading the to broken package and reporting issues?

**Pull request merged**
