### PR TITLE
mark bad pytest-executable

### PR DESCRIPTION
**Pull request by AntoineD**
Checklist:

* [ ] Added a link to the relevant issue in the PR description.
* [X] Pinged the team for the package.
<!--
  For example if you are trying to mark a python package as broken.

      ping @conda-forge/python
--!>
ping @conda-forge/python

### CODE REVIEW

**Comment by beckermr** [comment]
you need to ping @conda-forge/pytest-executable

**Comment by AntoineD** [comment]
Oops, I misread the instructions, I am this package team.

**Comment by beckermr** [comment]
Do you have a link to the issue or how you fixed it?

**Comment by AntoineD** [comment]
There is no gh issue, I made mistakes in my first 2 recipes (the package is not noarch and I did not use a PR).
I'd like to remove them, at least the noarch one so the package does not appear as being noarch.

**Comment by AntoineD** [comment]
The marked packages still appear with [noarch](https://anaconda.org/conda-forge/pytest-executable), I though it would have been removed, is it normal?

**Comment by beckermr** [comment]
It will take ~30 minutes to an hour for them to not be in the main index.

**Comment by beckermr** [comment]
And they will still be on the website.

**Comment by beckermr** [comment]
this looks correct.

**Pull request merged**
