### PR TITLE
remove linux git 2.26.1

### PR DESCRIPTION
**Pull request by CJ-Wright**
xref: https://github.com/conda-forge/git-feedstock/issues/78

### CODE REVIEW

**Comment by isuruf** [comment]
You've installed an osx package on linux

**Comment by CJ-Wright** [comment]
how did I do that?

**Comment by isuruf** [comment]
You were playing with mamba with explicit URLs like `https://conda.anaconda.org/conda-forge/osx-64`, right?

**Comment by CJ-Wright** [comment]
yes but this was a standard git update command

**Comment by CJ-Wright** [comment]
```
christopher@christopher-ubuntu ~/dev/cf-scripts use_mamba $ conda update conda-forge-pinning --yes                                            
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/christopher/mc

  added / updated specs:
    - conda-forge-pinning


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-forge-pinning-2020.04.15.00.37.28|                1          10 KB  conda-forge
    git-2.26.1                 |  pl526h5e3e691_0        15.0 MB  conda-forge
    jedi-0.17.0                |   py37hc8dfbb8_0         807 KB  conda-forge
    jupyter_client-6.1.3       |             py_0          74 KB  conda-forge
    jupyterlab_server-1.1.1    |             py_0          24 KB  conda-forge
    libarchive-3.3.3           |    h3a8160c_1008         1.5 MB  conda-forge
    librsvg-2.48.3             |       h33a7fed_0         8.5 MB  conda-forge
    llvm-openmp-10.0.0         |       hc9558a2_0         2.8 MB  conda-forge
    lz4-c-1.9.2                |       he1b5a44_0         223 KB  conda-forge
    mistune-0.8.4              |py37h8f50634_1001          53 KB  conda-forge
    nbconvert-5.6.1            |   py37hc8dfbb8_1         487 KB  conda-forge
    pandoc-2.9.2.1             |                0        18.7 MB  conda-forge
    parso-0.7.0                |     pyh9f0ad1d_0          67 KB  conda-forge
    zstd-1.4.4                 |       h6597ccf_3         991 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        49.1 MB

The following packages will be UPDATED:

  conda-forge-pinni~                  2020.04.10.18.29.06-1 --> 2020.04.15.00.37.28-1
  git                                2.26.0-pl526hf241897_0 --> 2.26.1-pl526h5e3e691_0
  jedi                                0.16.0-py37hc8dfbb8_1 --> 0.17.0-py37hc8dfbb8_0
  jupyter_client                                 6.1.2-py_0 --> 6.1.3-py_0
  jupyterlab_server                              1.1.0-py_1 --> 1.1.1-py_0
  libarchive                            3.3.3-hc47fbbf_1007 --> 3.3.3-h3a8160c_1008
  librsvg                                 2.46.4-h33a7fed_2 --> 2.48.3-h33a7fed_0
  llvm-openmp                              9.0.1-hc9558a2_2 --> 10.0.0-hc9558a2_0
  lz4-c                                 1.8.3-he1b5a44_1001 --> 1.9.2-he1b5a44_0
  mistune                           0.8.4-py37h516909a_1000 --> 0.8.4-py37h8f50634_1001
  nbconvert                                    5.6.1-py37_0 --> 5.6.1-py37hc8dfbb8_1
  pandoc                                            2.9.2-0 --> 2.9.2.1-0
  parso                                          0.6.2-py_0 --> 0.7.0-pyh9f0ad1d_0
  zstd                                     1.4.4-h3b9ef0a_2 --> 1.4.4-h6597ccf_3



Downloading and Extracting Packages
jedi-0.17.0          | 807 KB    | ################################################################################################### | 100% 
parso-0.7.0          | 67 KB     | ################################################################################################### | 100% 
lz4-c-1.9.2          | 223 KB    | ################################################################################################### | 100% 
git-2.26.1           | 15.0 MB   | ################################################################################################### | 100% 
mistune-0.8.4        | 53 KB     | ################################################################################################### | 100% 
jupyter_client-6.1.3 | 74 KB     | ################################################################################################### | 100% 
pandoc-2.9.2.1       | 18.7 MB   | ################################################################################################### | 100% 
jupyterlab_server-1. | 24 KB     | ################################################################################################### | 100% 
conda-forge-pinning- | 10 KB     | ################################################################################################### | 100% 
librsvg-2.48.3       | 8.5 MB    | ################################################################################################### | 100% 
zstd-1.4.4           | 991 KB    | ################################################################################################### | 100% 
nbconvert-5.6.1      | 487 KB    | ################################################################################################### | 100% 
llvm-openmp-10.0.0   | 2.8 MB    | ################################################################################################### | 100% 
libarchive-3.3.3     | 1.5 MB    | ################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by isuruf** [comment]
Let's talk about it in the git-feedstock

**Pull request closed without merging**
