### PR TITLE
Remove some CuPy v7.2.0 packages

### PR DESCRIPTION
**Pull request by leofang**
Not sure if we can leave comments in the txt file, so let me explain here:

- The first two batches are PyPy builds (build numbers 2 & 3 x CUDA versions 9.2, 10.0, 10.1, 10.2). They should be marked broken because of the observation https://github.com/conda-forge/cupy-feedstock/issues/43#issuecomment-603032749.
- The rest two batches are CUDA 10.2 builds (build number 1 & 2 x CPython 3.6, 3.7, 3.8). They are broken because the fp16 headers are missed (conda-forge/cupy-feedstock#41).

@jakirkham, could you confirm the list is correct? Thanks!

### CODE REVIEW

**Comment by leofang** [comment]
Looks like we can't even have blank lines in the list...Let me modify the file and the PR description.

**Comment by isuruf** [comment]
Or fix the code to ignore blank lines and lines starting with `#`. :smile:

**Comment by isuruf** [comment]
nvm, we are deleting that file, so not worth the effort.

**Comment by leofang** [comment]
Oh, you meant `mark_broken.py`? I was just about to write a PR 🙂

**Comment by leofang** [comment]
https://github.com/conda-forge/cf-mark-broken/compare/master...leofang:ignore_lines

**Comment by isuruf** [comment]
Looks good. You also need to fix Line 24

**Comment by leofang** [comment]
#29 works.

**Comment by jakirkham** [comment]
Thanks Leo! Also thanks Isuru for the review! 😄

**Pull request merged**
